### ISSUE TITLE
newline CRLF?

### ISSUE THREAD

**Issue by pasturm** [eddelbuettel/rcpptoml#12]
According to https://github.com/toml-lang/toml, newline can be CRLF or LF. However, parseTOML() does not seem to parse CRLF files (only works with LF or CR).

RcppTOML 0.1.1, R 3.3.1, windows x64

**Comment by eddelbuettel** [comment]
That should really be standard OS semantics -- we are not forcing anything on top.   

If you get the file from somewhere else, can you try a `unix2dos` converter?   Also, we can now parse from string so worst case you could read the data first and then parse.

**Comment by pasturm** [comment]
Damned! After restarting R and reinstalling the package I cannot reproduce this any more, it now works as expected. No clue why it did not work in the first place...
Apologies for bothering.

**Comment by eddelbuettel** [comment]
No worries. Sometimes we get screw-ups like that. R is pretty good at abstracting this away, as are most libraries,
