### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by vpvijay87** [eddelbuettel/rcpptoml#19]
Can some one help us on this 

R version: 3.3.2
c++ version : 4.9.2

Error:

R CMD INSTALL RcppTOML_0.1.3.tar.gz 
* installing *source* package ‘RcppTOML’ ...
** package ‘RcppTOML’ successfully unpacked and MD5 sums checked
** libs
gcc -std=c++0x -std=c++0x -fPIC -I/opt/local/qr/qualifiedr/lib64/microsoft-r/9.0/lib64/R/include -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -DU_STATIC_IMPLEMENTATION -I"/opt/local/tools/library/amgenNonQualified/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Generated by using Rcpp::compileAttributes() -> do not edit by hand
 ^
In file included from /opt/local/tools/library/amgenNonQualified/Rcpp/include/RcppCommon.h:121:0,
                 from /opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp.h:27,
                 from RcppExports.cpp:4:
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h: In function 'long unsigned int Rcpp::internal::enterRNGScope()':
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h:81:9: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
         }
         ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h: In function 'long unsigned int Rcpp::internal::exitRNGScope()':
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h:87:9: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
         }
         ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h: In function 'SEXPREC* rcpp_get_stack_trace()':
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h:126:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 }
 ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h: In function 'SEXPREC* rcpp_set_stack_trace(SEXP)':
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h:132:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 }
 ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h: In function 'std::string demangle(const string&)':
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h:138:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 }
 ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h: In function 'void* dataptr(SEXP)':
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/routines.h:210:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 }
 ^
gcc -std=gnu99 -I/opt/local/qr/qualifiedr/lib64/microsoft-r/9.0/lib64/R/include -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -DU_STATIC_IMPLEMENTATION -I"/opt/local/tools/library/amgenNonQualified/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c init.c -o init.o
gcc -std=c++0x -std=c++0x -fPIC -I/opt/local/qr/qualifiedr/lib64/microsoft-r/9.0/lib64/R/include -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -DU_STATIC_IMPLEMENTATION -I"/opt/local/tools/library/amgenNonQualified/Rcpp/include"      -c parse.cpp -o parse.o
parse.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 // -*- mode: C++; c-indent-level: 4; c-basic-offset: 4; indent-tabs-mode: nil; -*-
 ^
parse.cpp: In function 'SEXPREC* getValue(const std::shared_ptr<cpptoml::base>&)':
parse.cpp:119:41: error: no matching function for call to 'Rcpp::DatetimeVector::DatetimeVector(int, const char [4])'
         Rcpp::DatetimeVector dt(1, "UTC");
                                         ^
parse.cpp:119:41: note: candidates are:
In file included from /opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp.h:61:0,
                 from parse.cpp:27:
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:34:9: note: Rcpp::DatetimeVector::DatetimeVector(int)
         DatetimeVector(int n) : GreedyVector<Datetime, DatetimeVector>(n) {}
         ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:34:9: note:   candidate expects 1 argument, 2 provided
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:33:9: note: Rcpp::DatetimeVector::DatetimeVector(SEXP)
         DatetimeVector(SEXP vec) : GreedyVector<Datetime, DatetimeVector>(vec) {}
         ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:33:9: note:   candidate expects 1 argument, 2 provided
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:31:11: note: Rcpp::DatetimeVector::DatetimeVector(const Rcpp::DatetimeVector&)
     class DatetimeVector : public GreedyVector<Datetime, DatetimeVector> {
           ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:31:11: note:   candidate expects 1 argument, 2 provided
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:31:11: note: Rcpp::DatetimeVector::DatetimeVector(Rcpp::DatetimeVector&&)
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:31:11: note:   candidate expects 1 argument, 2 provided
parse.cpp:133:41: error: no matching function for call to 'Rcpp::DatetimeVector::DatetimeVector(int, const char [4])'
         Rcpp::DatetimeVector dt(1, "UTC");
                                         ^
parse.cpp:133:41: note: candidates are:
In file included from /opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp.h:61:0,
                 from parse.cpp:27:
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:34:9: note: Rcpp::DatetimeVector::DatetimeVector(int)
         DatetimeVector(int n) : GreedyVector<Datetime, DatetimeVector>(n) {}
         ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:34:9: note:   candidate expects 1 argument, 2 provided
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:33:9: note: Rcpp::DatetimeVector::DatetimeVector(SEXP)
         DatetimeVector(SEXP vec) : GreedyVector<Datetime, DatetimeVector>(vec) {}
         ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:33:9: note:   candidate expects 1 argument, 2 provided
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:31:11: note: Rcpp::DatetimeVector::DatetimeVector(const Rcpp::DatetimeVector&)
     class DatetimeVector : public GreedyVector<Datetime, DatetimeVector> {
           ^
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:31:11: note:   candidate expects 1 argument, 2 provided
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:31:11: note: Rcpp::DatetimeVector::DatetimeVector(Rcpp::DatetimeVector&&)
/opt/local/tools/library/amgenNonQualified/Rcpp/include/Rcpp/DatetimeVector.h:31:11: note:   candidate expects 1 argument, 2 provided
make: *** [parse.o] Error 1
ERROR: compilation failed for package ‘RcppTOML’

**Comment by eddelbuettel** [comment]
Let me quote from DESCRIPTION:

> SystemRequirements: A C++11 compiler; g++ (>= 4.8.*) should be fine.

There is an issue here because you say g++-4.9, yet your `R CMD INSTALL` shows  
`-std=c++0x -std=c++0x` indicating that maybe your R version was built with an older compiler -- and the settings from R's build matters.

In short, nothing wrong with RcppTOML.  This appears to be your local setup.

**Comment by vpvijay87** [comment]
Hi Dirk,

Thanks a lot for reply.

We have added the command "CXX1X=gcc -std=c++0x" in the Makeconf file.

Do you have any suggestions to update the compiler, so that I will take it
forward.

Thanks in Advance.

Regards,
Pravin

On Wed, Jul 26, 2017 at 5:18 PM, Dirk Eddelbuettel <notifications@github.com
