### ISSUE TITLE
Does UTF encoding work?

### ISSUE THREAD

**Issue by Radibor** [eddelbuettel/rcpptoml#20]
I save the following TOML_test file in UTF-8 (on Windows 10) :

title = "TOML Example"
[owner]
name = "äöüßà"

> parseTOML("J:/my/path/TOML_test.toml")
List of 2
 $ owner:List of 1
  ..$ name: chr "Ã¤Ã¶Ã¼ÃŸÃ "
 $ title: chr "TOML Example"

There is no such issue with yaml:
> yaml.load_file("J:/my/path/YAML_test.yaml")
$`Überschrift`
$`Überschrift`$Typ
[1] "äöüßà"

**Comment by eddelbuettel** [comment]
It works fine under Linux:

```r
> parseTOML("/tmp/check.toml")
List of 2
 $ owner:List of 1
  ..$ name: chr "äöüßà"
 $ title: chr "TOML Example"
>
```

Someone would need to trace where the Windows side of things is loosing it.

**Comment by eddelbuettel** [comment]
Sorry for not acting on this earlier, but this should now be better thanks to #30.

If however it is not, please re-open the ticket.

**Comment by Radibor** [comment]
Thanks for letting me know and fixing it! It works for me, too.

Regards
Wolfgang
________________________________
Von: Dirk Eddelbuettel <notifications@github.com>
Gesendet: Samstag, 27. Oktober 2018 00:58
An: eddelbuettel/rcpptoml
Cc: Radibor; Author
Betreff: Re: [eddelbuettel/rcpptoml] Does UTF encoding work? (#20)


Sorry for not acting on this, but this should now be better thanks to #30<https://github.com/eddelbuettel/rcpptoml/pull/30>.

**Comment by eddelbuettel** [comment]
Thanks for reporting back, again my bad for not addressing it earlier -- and thanks to @vh-d for fixing it.
