### ISSUE TITLE
A windows version?

### ISSUE THREAD

**Issue by einian85** [eddelbuettel/rcpptoml#3]
I think the title is obvious. I know there are problems with Rtools C++ compiler, but so what? what would happen? will you wait until some unknown day that Rtools will upgrade?

**Comment by eddelbuettel** [comment]
> but so what?

I am not sure you really understand the issue. `g++-4.6.*` simply _cannot_ compile the C++11 code used here.   Which is pretty much what I try to say in DESCRIPTION.

So yes, if and when we have a new Rtools based on `g++-4.9` (or newer) we will get RcppTOML for Windows.  And no, I do know when that may be.  There are efforts underway to get a new Rtools for R 3.3 next spring.  But that was also planned for R 3.2 this spring ...

**Comment by krlmlr** [comment]
It seems that at least winbuilder is now capable of building the package on Windows ([r-devel](http://win-builder.r-project.org/y3McVWXzs7tQ/00check.log) _and_ [r-stable](http://win-builder.r-project.org/uvH13n6Evc4X/00check.log)). Is a CRAN re-release the easiest way to add Windows binaries to CRAN?

**Comment by eddelbuettel** [comment]
Details?  How does one turn on the newer compiler needed for this?

**Comment by krlmlr** [comment]
I changed nothing but maintainer name and e-mail address in DESCRIPTION.

**Comment by eddelbuettel** [comment]
Can you point me to anything by Uwe that talks about when compiler is now used?  

AFAIK Rtools3.3.exe is not yet finished; and the last comment by Duncan that I saw reiterated.  So I'd urge patience. 

I have a few other packages that would benefit from this...

**Comment by krlmlr** [comment]
...and I stand corrected: winbuilder doesn't throw up, but doesn't build binaries either. Drat :-)

Other people build C++11 packages using the new Rtools 3.3 toolchain on AppVeyor (CC @wush978). One might use that to publish binaries to drat, but this looks like it takes some effort.

**Comment by eddelbuettel** [comment]
And then you may still get into hot water for mixing different g++ versions -- though 4.6 to 4.9 should be safe.

**Comment by eddelbuettel** [comment]
Old thread ... but we just merged code that makes it possible to build on Windows.  

Super excited, and nice work with @dpastoor to get there.
