### ISSUE TITLE
Support TOML v0.5.0?

### ISSUE THREAD

**Issue by KeitoTobi1** [eddelbuettel/rcpptoml#33]
Since `cpptoml` seems to be compatible with [v0.5.0](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md), will this correspond to me?

**Comment by eddelbuettel** [comment]
What exactly is your question?  We _do_ support v0.5.0 since the last two releases, see [the NEWS file](https://cloud.r-project.org/web/packages/RcppTOML/news.html) and check particularly the last item for 0.1.4:

> Synchronized with new upstream cpptoml version supporting the TOMP v0.5.0 specification. (#25)

Is that what you are looking for?
