### ISSUE TITLE
Consider newer C++ libraries to get TOML 1.0 compliance

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcpptoml#44]
As it looks like [cpptoml](https://github.com/skystrife/cpptoml) is stale at hence "forever" stuck at TOML 0.5 compliance, it may make sense to look at 

- [tomlcpp](https://github.com/cktan/tomlcpp) (uses library)
- [tomlplusplus](https://github.com/marzer/tomlplusplus)  (header-only, C++17)
- [toml11](https://github.com/ToruNiina/toml11) (header only, C++11)

instead.

**Comment by homalozoa** [comment]
Perhaps we can talk about new lib here...

**Comment by eddelbuettel** [comment]
Indeed.  Over at https://github.com/skystrife/cpptoml/pull/123 was really overusing that repo -- I should have noticed earlier.

I am game. We could use a branch here.  Or start a new one, maybe even under a temp name (rcpptoml2 ?) before we settle.  Starting with `tomlplusplus` is fine by me (as using a header-only library is extra portable).

**Comment by homalozoa** [comment]
`rcpptoml2` is a good name, I think `rcpptomlplusplus` is too lengthy.  Should we distinguish 0.5 compliance and 1.0 compliance clearly? If not, we can just create a branch. If so, perhaps we should create a new repo.

**Comment by eddelbuettel** [comment]
I'll set something up tomorrow morning. I like RcppTomlPlusPlus is that is what we go with.

**Comment by eddelbuettel** [comment]
Thanks for the nudge.  We now have https://github.com/eddelbuettel/rcpptomlplusplus and it provides the minimal working example (of just displaying to standard output). After `R CMD build .` and `R CMD INSTALL RcppToml*tar.gz` you can do

```r
> library(RcppTomlPlusPlus)
> example(simpleParser)     # renamed, I like camelCase
```

which will print out the `example.toml` also included in the package.

**Comment by eddelbuettel** [comment]
This is now taken care of in this branch which I may soon PR and send to CRAN:
https://github.com/eddelbuettel/rcpptoml/tree/feature/tomlplusplus
