### ISSUE TITLE
parse.o Error 1 compilation failed for package 'RcppTOML' when attempting package install.

### ISSUE THREAD

**Issue by yechoi942** [eddelbuettel/rcpptoml#46]
Hi,

I'm using R version 4.0.2 and have it installed on a RedHat 7 platform.
I've tried running install.packages("RcppTOML") but the following message pops up:

                                                               ^
make: *** [parse.o] Error 1
ERROR: compilation failed for package ‘RcppTOML’
* removing ‘/z/yechoi/R/x86_64-pc-linux-gnu-library/4.0/RcppTOML’

The downloaded source packages are in
   ‘/tmp/RtmpHb0Eca/downloaded_packages’
Warning message:
In install.packages("RcppTOML") :
 installation of package ‘RcppTOML’ had non-zero exit status

As I am not coding-savvy, I need some help in understanding what's happening and how to resolve this issue.

Thanks,
Yehyun

**Comment by eddelbuettel** [comment]
There is an inherent conflict between the use of RedHat 7 ("stable", which here means "old compiler") and your desire to use code requoring a newer compiler. 

Frankly, I recommend not using old RedHat (or CentOS or RockyOS or ...) releases.   If you have no choice in the matter try to look into `devtoolset` for RHEL/CentOS/...:  https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/  There are different versions, it helped me once years when I was forced to work on CentOS.

Good luck, but I am closing this as it is not really an issue cause by RcppTOML.
