### ISSUE TITLE
Install problems with RcppTOML - headers not found

### ISSUE THREAD

**Issue by kelbstf** [eddelbuettel/rcpptoml#48]
Hello,

we face problems with 
upgrading (0.1.3-0.1.7)/installing (0.1.7) RcppTOML in this environment 

1. R4.2.1, 
2. g++ (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3) [devtools-8], 
3. make --version GNU Make 4.2.1
4. R-Makevars: g++17. 

Compilation of RcppTOML selects "g++ -std=gnu++11".

This exact same environment/R implementation 
allowed installing RFast (2.0.6) in the previous step 
with no issues, 
which has "SystemRequirements: C++17".

**Environment:**
<pre>
# gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
# g++ --version
g++ (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
# make --version
GNU Make 4.2.1

# $(gcc -print-prog-name=cc1) --help | grep std
  -Wintrinsics-std            		[disabled]
  -std=extra-legacy           		
  -std=f2003                  		
  -std=f2008                  		
  -std=f2008ts                		
  -std=f2018                  		
  -std=f95                    		
  -std=gnu                    		
  -std=legacy                 		
  -fobjc-std=objc1            		[disabled]
  -nostdinc                   		
  -nostdinc++                 		
  -nostdlib                   		
  -std=c++03                  		
  -std=c++11                  		
  -std=c++14                  		
  -std=c++17                  		
  -std=c++2a                  		
  -std=c++98                  		
  -std=c11                    		
  -std=c17                    		
  -std=c18                    		
  -std=c1x                    		
  -std=c89                    		
  -std=c90                    		
  -std=c99                    		
  -std=c9x                    		
  -std=gnu++03                		
  -std=gnu++11                		
  -std=gnu++14                		
  -std=gnu++17                		
  -std=gnu++2a                		
  -std=gnu++98                		
  -std=gnu11                  		
  -std=gnu17                  		
  -std=gnu18                  		
  -std=gnu1x                  		
  -std=gnu89                  		
  -std=gnu90                  		
  -std=gnu99                  		
  -std=gnu9x                  		
  -std=iso9899:1990           		
  -std=iso9899:199409         		
  -std=iso9899:1999           		
  -std=iso9899:199x           		
  -std=iso9899:2011           		
  -std=iso9899:2017           		
  -std=iso9899:2018           		
  -fstdarg-opt                		[enabled]
</pre>
<pre>
# R
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
</pre>

<pre>
# /usr/include/c++
total 24
drwxr-xr-x.  3 root root    45 Jun 28 16:04 .
drwxr-xr-x. 92 root root 12288 Feb  7 11:52 ..
drwxr-xr-x. 12 root root  4096 Jul 12  2021 4.8.2
lrwxrwxrwx.  1 root root     5 Jul 12  2021 4.8.5 -> 4.8.2
lrwxrwxrwx.  1 root root    43 Jun 28 16:04 8.3.1 -> /opt/rh/devtoolset-8/root/usr/include/c++/8
</pre>

<pre>
# echo $LD_LIBRARY_PATH
/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib
</pre>

**Failure report:**

<pre>
> update.packages()
RcppTOML :
 Version 0.1.3 installed in /opt/R/4.2.1/lib/R/library 
 Version 0.1.7 available at https://ftp.fau.de/cran
Update? (Yes/no/cancel) y
trying URL 'https://ftp.fau.de/cran/src/contrib/RcppTOML_0.1.7.tar.gz'
Content type 'application/x-gzip' length 42551 bytes (41 KB)
==================================================
downloaded 41 KB

* installing *source* package ‘RcppTOML’ ...
** package ‘RcppTOML’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/opt/R/4.2.1/lib/R/include" -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -I'/opt/R/4.2.1/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/opt/R/4.2.1/lib/R/include" -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -I'/opt/R/4.2.1/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c parse.cpp -o parse.o
In file included from parse.cpp:28:0:
../inst/include/toml.hpp: In static member function ‘static std::string includize::toml_spec<char>::unescape_filename(const string&)’:
../inst/include/toml.hpp:29:66: error: no matching function for call to ‘regex_replace(const string&, std::regex, const char [2])’
         return std::regex_replace(str, std::regex("\\\\\""), "\"");
                                                                  ^
../inst/include/toml.hpp:29:66: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../inst/include/includize.hpp:7,
                 from ../inst/include/toml.hpp:4,
                 from parse.cpp:28:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
In file included from parse.cpp:28:0:
../inst/include/toml.hpp:29:66: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
         return std::regex_replace(str, std::regex("\\\\\""), "\"");
                                                                  ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../inst/include/includize.hpp:7,
                 from ../inst/include/toml.hpp:4,
                 from parse.cpp:28:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
In file included from parse.cpp:28:0:
../inst/include/toml.hpp:29:66: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [2]’
         return std::regex_replace(str, std::regex("\\\\\""), "\"");
                                                                  ^
make: *** [parse.o] Error 1
ERROR: compilation failed for package ‘RcppTOML’
* removing ‘/opt/R/4.2.1/lib/R/library/RcppTOML’
* restoring previous ‘/opt/R/4.2.1/lib/R/library/RcppTOML’

The downloaded source packages are in
	‘/tmp/RtmpfpnJuK/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘RcppTOML’ had non-zero exit status
> 
</pre>
**Analysis:**
If one actually reads the error log, one finds it's actually the headers that are not properly picked up, 
although the headers belonging to the used compiler are available in the standard path:
<pre>
# /usr/include/c++
total 24
drwxr-xr-x.  3 root root    45 Jun 28 16:04 .
drwxr-xr-x. 92 root root 12288 Feb  7 11:52 ..
drwxr-xr-x. 12 root root  4096 Jul 12  2021 4.8.2
lrwxrwxrwx.  1 root root     5 Jul 12  2021 4.8.5 -> 4.8.2
lrwxrwxrwx.  1 root root    43 Jun 28 16:04 8.3.1 -> /opt/rh/devtoolset-8/root/usr/include/c++/8
</pre>
<pre>
# /usr/include/c++/4.8.2/bits/regex.h
-rw-r--r--. 1 root root 85498 Sep 30  2020 /usr/include/c++/4.8.2/bits/regex.h
# /usr/include/c++/8.3.1/bits/regex.h
-rw-r--r--. 1 root root 97402 Mar 27  2020 /usr/include/c++/8.3.1/bits/regex.h
</pre>

Instead the false old compiler's header version is chosen over the header version belonging to the currently used compiler. Which must fail, because regex prototype is not implemented in 4.8.2.

Comparison of make config in source for both R-packages unveils following difference:
<pre>
RFast: PKG_CPPFLAGS = -I../inst/include
RcppTOML: PKG_CPPFLAGS = -I../inst/include/ -DCPPTOML_USE_MAP
</pre>

Can't figure out whether/how -DCPPTOML_USE_MAP might contribute to this different behaviour/outcome of detecting the proper headers belonging to the already successfully detected compiler which would meet the requirements of RcppTOML otherwise.

Best

**Comment by eddelbuettel** [comment]
That's between and your R installation. RcppTOML ships its headers, R reliably finds those.  I unfortunately do not have the time now to read and debug your 100+ line report.  Sorry.  

Maybe try the rcpp-devel list, or better still (it if exists?) a CentOS list to get help from other folks forced to fight with two hands tied behind their back.

If you don't mind, I would like to close this as there is no conceivable error with RcppTOML as the CRAN results page shows:

![image](https://user-images.githubusercontent.com/673121/176232588-fa01b30e-3dd8-4006-a6d7-15c9202704f6.png)

**Comment by eddelbuettel** [comment]
PS If I had to guess it may the addition of devtoolset (a good move!) confusing what R has written down for itself about headers etc.  Worst case you may have to quickly rebuild R under devtoolset.  It's been years since I was forced^Hhad the distinct pleasure to work on CentOS so I no longer know the tricks.  If you can find some CentOS/RHEL specific tutorials...

**Comment by kelbstf** [comment]
Thank you very much for answering so quick, i really appreciate it.
Actually it's 2 lines:

<pre>
../inst/include/toml.hpp:29:66: error: no matching function for call to ‘regex_replace(const string&, std::regex, const char [2])’
         return std::regex_replace(str, std::regex("\\\\\""), "\"");


../inst/include/toml.hpp:29:66: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../inst/include/includize.hpp:7,
                 from ../inst/include/toml.hpp:4,
                 from parse.cpp:28:
</pre>
where "/usr/include/c++/8.3.1" is missing...

And since this exact step succceeds for RFast (depending on C++17), i sensed the problem might be linked to Makevars "-DCPPTOML_USE_MAP", where RcppTOML differs from RFast...
I just hoped this differentce would ring a bell with you allowing you a quick drop in solution.

I totally understand your situation, sounds familiar.
Unfortunately, i'll have to find a solution, since this will have to run on a HPC cluster soon, where deb-based systems currently have a representaion of 1,4% according to top500.org. So rpm is a given, and switching between toolchains in a modular software stacks a requirement...

I'll dig deeper then and start with your idea to check the R-devtool-interaction  ;-)

If i find a solution, i'll get back here and will post it.

Thank you again,

Best

**Comment by eddelbuettel** [comment]
You could try flipping the C++ standard to C++14 or C++17 to see if that works and `g++` 8.3.* can help here:

https://github.com/eddelbuettel/rcpptoml/blob/cb4d0a05f4ecaeeb3788a43c3eecb243accbdb7a/src/Makevars#L2-L3

**Comment by eddelbuettel** [comment]
(And it really has zero to do with deb versus rpm. People who insist on Ubuntu 14.04 or 16.04 (or ancient Debian releases) can be similarly hosed.

It is 2022.  Tools from 2022 or 2021 work great. I enjoy them.  I know your hands are tied but I must stress that the trouble is in fact self-imposed.  Everybody around your cluster means well but it is a massive "make-work" project this way.  Anyway....)
