### ISSUE TITLE
RcppTOML requires newer version of Rcpp

### ISSUE THREAD

**Issue by waltersom** [eddelbuettel/rcpptoml#53]
RcppTOML now requires a newer version of Rcpp (>=1.0.8) to compile, rather than the version specified in the DESCRIPTION file (>=0.11.5).

This is due to the change to link against Rcpp/Lightest in 00cce5c6949a3ae04579cba8235f20c0486af629, which was only introduced in Rcpp 1.0.8.

**Comment by eddelbuettel** [comment]
Good catch, and my bad.  The entry in DESCRIPTION in kinda automatic / stale.
