### ISSUE TITLE
parse from string

### ISSUE THREAD

**Issue by dpastoor** [eddelbuettel/rcpptoml#7]
While updating - one other request would be - I see that you are calling https://github.com/eddelbuettel/rcpptoml/blob/master/src/parse.cpp#L198 for this implementation, but can you think of a reasonable workaround for parsing a string rather than a file, other than writing it out to tmp/ then parsing that?

Namely, one use that I have is giving some structure to comments inside a comment block of a file.

For example, a control stream for the nonlinear mixed effect modeling language that I use looks like:

```
$PROB <some text>
;; comments
;; ...
$PK
...
```

Where the current practice is just to parse text

```
;; based on: <some prior model>
;; details: <some text>
```

whereas I would like to do

```
;; based_on = <prior model>
;; [details]
;; comment1 = <text>
;; comment2 = <more text>
;; [etc]
```

as white space is so flexible in toml it makes it perfect for just stripping the proceeding `;;` and then parsing the rest.

Worst case after stripping I'll just write it out to a tmp file then parse that in, but it would be cool to just be able to concat the relevant lines and pass that string to a `parse_toml()` function

**Comment by eddelbuettel** [comment]
I was about to blurb off that 

>  From the top of my head, you don't need that. Look into the (wonderful) R Connections; 
> maybe start with `help(connections)`

but then I checked, and we pass the _filename_ down, not the stream.   So with that we'd have a little bit or work to do, but probably not a hell of a lot.  And I like the idea.

**Comment by eddelbuettel** [comment]
Then again, looking at the C++ layer of `tomlParseImpl()` I get flashbacks of when I wrote that -- I am not too familiar with parsers, and the recursive nature of this made it tricky.

Then again and minimum we could cheat and dump temporary textual content to a file, or do something else.  Upstream may also have views on this.  Still worth considering.

**Comment by dpastoor** [comment]
Yeah I think that a temp file is going to be the way to go, for better or worse. I would think there are bigger fish to fry than spending too much time trying to it figure out. 

If you want, I can create a PR for a simple tempfile() based solution called something like `parse_toml_string()` or I guess to maintain internal consistency `parseTOMLstring` or `parsetomlstring`

**Comment by eddelbuettel** [comment]
I would be delighted to review a clean and simple PR like that.  But give me a moment (think: day or two) as I think I should get our "joint" PR out of the way, and think about merging upstream (which should be straightforward).

A first version would be trivial. R gives us a temp directory which is guaranteed to be cleaned.  We could just go there, and be done.  All in R.

I did like your general ideas though.  We can start small with something like this, and then go from there with some interesting 'markup for modeling'.  I think we are both on the same page: toml rocks, is typed, and all the lighter-weight stuff if _fundamentally_ inferior.

**Comment by skystrife** [comment]
A more simple workaround (but one that involves writing C++) might be to use a `std::stringstream` and a `cpptoml::parser` directly.

You would change a line like
```cpp
auto table = cpptoml::parse_file(filename);
// ...
```

to

```cpp
std::string str = /* string containing TOML you got from somewhere */;
std::stringstream strstream(str);
cpptoml::parser p(strstream);
auto table = p.parse();
// ...
```

**Comment by eddelbuettel** [comment]
Oh, that is a very good point. Another TODO item!

I also noticed that you now have `operator<<()` for the TOML tree, so I should probably offer a way to save a config. I always hesitated because to me TOML _on input_ was always richer with comments and possible indentation etc -- and _on output_ we won;t have that.  Oh well.  People can always hand-edit.

**Comment by eddelbuettel** [comment]
Thanks for the hint, @skystrife -- that approach works like charm as I just established with a quick check on the (short-ish for me) commuter train ride.

@dpastoor What shall we do interface-wise? Keep as is, and if the supplied string is NOT a file (as seen from `file.exists()` failing) we parse from string?   Or an explicit bool to have the user demand parse frim string (which is what my not-yet-committed first pass does) ?

**Comment by dpastoor** [comment]
@eddelbuettel I have never minded being explicit, and makes the internals simpler. The two benefits two 'guessing' the type, imo, are 

1) Its the way modern ingestion packages like readr are doing it, so users may expect that type of behavior
2) it makes it easier to support multiple types - eg if we also wanted to support a connection/stream/etc down the line.

_if_ the desire is to go down that route, the readr package I think reasonably elegantly demonstrates a robust implementation of string/connection/filepath - overkill for what would likely be needed for this - but definitely can pull inspiration from.

datasource detection - https://github.com/tidyverse/readr/blob/3715a2d0bcd7e028b4c0ffe03fce0fd7063ede18/R/source.R#L34

All said, I don't think you'd go wrong either way, and it would not bother me in the slightest having a bool flag.

**Comment by eddelbuettel** [comment]
You are seemingly contradicting yourself, arguing both for being explicit AND for implicit guessing.

And I not going to take readr as an example. I mostly avoid the whateververse.  Once burnt, twice shy.  Just was forced to make another change today as it seemingly cannot keep its APIs stable.

**Comment by eddelbuettel** [comment]
In short I'll let it rest. I may commit what I have, and/or may change it.  The bigger work piece outstanding is to reverse a parse -- convert an R list into a TOML table so that we can write it out.

**Comment by dpastoor** [comment]
Yeah my point was that I don't have a preference, and can see the pros/cons of each. 

And I think you are very correct that a better use of time is tackling a writer

**Comment by eddelbuettel** [comment]
This is done in #10.

**Comment by eddelbuettel** [comment]
And that version is now on CRAN.
